### ISSUE TITLE
Research PHP Websockets

### ISSUE THREAD

**Issue by jackjamieson** [jackjamieson/harmony#10]
We can use this for knowing who is in the room and the chat service.

**Comment by jkidd93** [comment]
in our previous meeting you said you got chat working right?

**Comment by jackjamieson** [comment]
I got a server running that supported chat but we need to support separate
rooms. I'll show you where I found the tutorial tomorrow

**Comment by jkidd93** [comment]
yeah i found a chat tutorial and it worked when setting the server up locally in the terminal and running it with index.html. Me and sam tried to check if it would work on his webpage instead of setting the server up manually through the terminal, but as he said in the groupchat, it doesn't work
